export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';


export const SENDING_REQUEST = 'SENDING_REQUEST';


export const LOGIN__MISSING_FIELD = 'LOGIN__MISSING_FIELD';
export const LOGIN__FAILED = 'LOGIN__FAILED';
