export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';


export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';


export const LOGIN__SUCCESS = 'LOGIN__SUCCESS';
export const LOGIN__FAILED = 'LOGIN__FAILED';
export const LOGOUT__SUCCESS = 'LOGOUT__SUCCESS';



export const PROFILE__REQUESTING = 'PROFILE__REQUESTING';
export const PROFILE__SUCCESSFULLY_RECEIVED = 'PROFILE__SUCCESSFULLY_RECEIVED';
export const PROFILE__FAILED_RECEIVING = 'PROFILE__FAILED_RECEIVING';


export const CHANGE_PASSWORD__REQUESTING = 'CHANGE_PASSWORD__REQUESTING';
export const CHANGE_PASSWORD__SUCCESSFULLY_RECEIVED = 'CHANGE_PASSWORD__SUCCESSFULLY_RECEIVED';
export const CHANGE_PASSWORD__FAILED_RECEIVING = 'CHANGE_PASSWORD__FAILED_RECEIVING';
