export const SENDING_REQUEST = 'SENDING_REQUEST';


export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';


export const LOGIN__REQUESTED = 'LOGIN__REQUESTED';
export const LOGIN__SUCCEEDED = 'LOGIN__SUCCEEDED';
export const LOGIN__COMPLETED = 'LOGIN__COMPLETED';
export const LOGIN__FAILED = 'LOGIN__FAILED';


export const LOGOUT__REQUESTED = 'LOGOUT__REQUESTED';
export const LOGOUT__SUCCESS = 'LOGOUT__SUCCESS';


export const REGISTRATION__REQUESTED = 'REGISTRATION__REQUESTED';
export const REGISTRATION__SUCCESSFULLY_RECEIVED = 'REGISTRATION__SUCCESSFULLY_RECEIVED';
export const REGISTRATION__FAILED_RECEIVING = 'REGISTRATION__FAILED_RECEIVING';


export const PROFILE__REQUESTED = 'PROFILE__REQUESTED';
export const PROFILE__SUCCESSFULLY_RECEIVED = 'PROFILE__SUCCESSFULLY_RECEIVED';
export const PROFILE__FAILED_RECEIVING = 'PROFILE__FAILED_RECEIVING';


export const CHANGE_PASSWORD__REQUESTED = 'CHANGE_PASSWORD__REQUESTED';
export const CHANGE_PASSWORD__SUCCESSFULLY_RECEIVED = 'CHANGE_PASSWORD__SUCCESSFULLY_RECEIVED';
export const CHANGE_PASSWORD__FAILED_RECEIVING = 'CHANGE_PASSWORD__FAILED_RECEIVING';



